# .streamlit/secrets.toml

[connections.snowpark]
account = "UQTWJKQ.UVA11212"
user = "matt_allison"
password = "DaleBenJackAreMy3Sons"
role = "Admin"
warehouse = "IRP_DB"
database = "IRP_DB"
schema = "PUBLIC"
client_session_keep_alive = true
